// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_uk1r96pyGb1Ktyqf7b9GFMbHpfodBdI',
    appId: '1:798004906514:web:7c91a29f1d53b7583fa6cb',
    messagingSenderId: '798004906514',
    projectId: 'agrimate-ed008',
    authDomain: 'agrimate-ed008.firebaseapp.com',
    storageBucket: 'agrimate-ed008.firebasestorage.app',
    measurementId: 'G-K8FSP45T8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtJA_Cy1pLTypEdDIn7geR9dTqVVzfw4',
    appId: '1:798004906514:android:773e57649ef90e153fa6cb',
    messagingSenderId: '798004906514',
    projectId: 'agrimate-ed008',
    storageBucket: 'agrimate-ed008.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_uk1r96pyGb1Ktyqf7b9GFMbHpfodBdI',
    appId: '1:798004906514:web:85fa44e9c1ac0a443fa6cb',
    messagingSenderId: '798004906514',
    projectId: 'agrimate-ed008',
    authDomain: 'agrimate-ed008.firebaseapp.com',
    storageBucket: 'agrimate-ed008.firebasestorage.app',
    measurementId: 'G-XPF38E3DMM',
  );
}
